[package]
name = "export-data"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "export_data provides functions to export data."
authors = ["GNahcab"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manipulate-data = { path = "../manipulate-data", version = "0.1.0" }
parquet.workspace = true
arrow.workspace = true
chrono.workspace = true
